config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resource :users do 
    get 'signin', on: :collection
    post 'login', on: :collection 
  end
  resources :categories do 
    get 'particular_category_products', on: :member
  end
  resources :products do 
    get'current_user_products', on: :collection
  end
  resources :purchases do 
    get 'buy', on: :member
    get 'current_user_sold_products', on: :collection
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.
    if user.present?
        can [:create, :index, :update_product, :destroy,:current_user_products], Product, user_id:user.id
        can  [:index, :current_user_sold_products], Purchase, user_id:user
        cannot :create, Purchase, user_id: user.id
        # can :update, User, id:user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one :purchase
  has_one_attached :product_profile

  enum status: {available: "available", sold:"sold"}

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :product

end

app/models/user.rb
class User < ApplicationRecord
	has_many :products
	has_many :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include JsonWebToken
  before_action :authenticate_user

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "You can not access"
    # redirect_to :back
  end
rescue_from ActiveRecord::RecordNotFound do |exception|
   flash[:notice] = "You can not access"
    # redirect_to :back
 end
  def current_user
    @current_user
  end

  def authenticate_user
    begin
      decoded = jwt_decode(session[:current_user].split(' ').last)
      @current_user = User.find_by_email(decoded[:email])
      raise unless @current_user.present?
    rescue StandardError
      flash[:notice] = "Unauthorize User"
      redirect_to signin_users_path
     # render html: helpers.tag.strong('Unauthorized')
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	def index
	end

	def particular_category_products
		@category_products = Product.joins(:category).available.merge(Category.where(id:params[:id]))
		@category = Category.find_by(id:params[:id])
	end
end

app/controllers/concerns/json_web_token.rb
require "jwt"

module JsonWebToken
	extend ActiveSupport::Concern
	SECRET_KEY = Rails.application.secret_key_base

	def jwt_encode(payload,exp = 7.days.from_now)
		payload[:exp]=exp.to_i
		JWT.encode(payload,SECRET_KEY)
	end	

	def jwt_decode(token)
		decoded = JWT.decode(token,SECRET_KEY)[0]
		HashWithIndifferentAccess.new decoded
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	load_and_authorize_resource 

	def new
	end

	def create
		product = @current_user.products.new(product_params)
		if product.save
			product.alphanumeric_id = generate_alphanumeric(params[:name])
			product.available!
			redirect_to products_path
		else
			render 'new'
		end
	end

	def index
 	@products =	if params[:name].present?		 
									Product.available.where("name like ?","%#{params[:name]}%")
						    elsif params[:alphanumeric_id].present?
						    	Product.available.where("alphanumeric_id like ?","%#{params[:name]}%")
						    elsif params[:category_name].present?
					  	  	Product.joins(:category).available.merge(Category.where("category_name like ?","%#{params[:name]}%"))
						    else
						    	Product.available
								end		

	end

	def current_user_products
		@products = @current_user.products.available
	end

	private

	def generate_alphanumeric(value)
		random_num = rand(1000)
	 	data = value + "#{random_num}"
	 	return data
	end
	
	def product_params
		params.permit(:name, :description, :price,  :category_id, :product_profile)
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
		load_and_authorize_resource 

	def new

	end

	def buy
		# @purchase = Purchase.new(user_id:@current_user.id, product_id:params[:id])
		product = Product.available.find_by(id:params[:id]).accessible_by(current_ability)
		purchase = @current_user.purchases.new(product_id: product.id)
	 	purchase.save
		product.sold!
		
			# render html: helpers.tag.strong("product buy sucessfully...")	
	end
	
	def current_user_sold_products
		@purchases = @current_user.products.sold 
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :authenticate_user, only:[:new,:login,:create,:signin]
  include JsonWebToken
	def new
	end

	def create
		@user = User.new(user_params)
		if @user.save
      session[:current_user] = jwt_encode(email: @user.email)
			redirect_to products_path
		else
			render 'new'
		end
	end

	def login
    @user = User.find_by(email: params[:email])   
    if  @user.password == params[:password]
      session[:current_user] = jwt_encode(email: @user.email)
      redirect_to products_path
    else
      flash[:notice] = "Unauthorize User"
      redirect_to signin_users_path
    end
  
  end

	def destroy
    # Remove the user id from the session
    session.delete(:current_user)
    # Clear the memoized current user
    @current_user = nil
    redirect_to new_users_path
  end

  def signin
  end
  
	private

	def user_params
		params.permit(:first_name, :last_name, :email, :mobile_no, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
  <%  Category.all.each do |category| %>
    <li><%= button_to category.category_name,   particular_category_products_category_path(category), method: :get %></li>    
  <% end %>
</ul>

<%= button_to "Back", products_path, method: :get %>

app/views/categories/particular_category_products.html.erb
<h1> <%= @category.category_name %> </h1>
<ul>
  <% @category_products.each do |product| %>
    <li>
        Name:<%= product.name %><br>
        Price:<%= product.price  %><br>
        Description:<%= product.description %><br>
        Image:<%= image_tag(product.product_profile) %> <br>
        <% if @current_user.id == product.user_id %>
         This is your product
        <% else %>
        <%= button_to "Buy", buy_purchase_path(product.id), method: :get %>
        <% end %>  
      </li>
  <% end %>

</ul>

<%= button_to "Back", categories_path, method: :get %> <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OlxSession</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/current_user_products.html.erb
<h1> <%=@current_user.first_name %> Products</h1>

<ul>
  <% @products.each do |product| %>
    <li>
        Name:<%= product.name %><br>
        Price:<%= product.price %><br>
        Description:<%= product.description %><br>
        Image:<%= image_tag(product.product_profile) %> <br>
        <%= button_to "Buy", buy_purchase_path(product.id), method: :get %>
      </li>
  <% end %>

</ul>
 
   <%= button_to "Back", products_path, method: :get %> <br>
  <%= button_to "New Product", new_product_path, method: :get %><br>
  <%= button_to "Sign_out", users_path, method: :delete %>

app/views/products/index.html.erb
 <%= button_to "My Products", "/products/current_user_products", method: :get %>
 <%= button_to "My Purchasing", "/purchases/current_user_sold_products", method: :get %>

   <%= button_to "CATEGORIES", categories_path, method: :get %> <br>

  <%= button_to "Sign_out", users_path, method: :delete %> <br>

<h1>Products</h1>
  <%= form_with url: "/products", method: :get do |form| %>
  <%= form.label :name, "Search for:" %>
  <%= form.text_field :name ,placeholder:"Find Cars, Mobile Phones and more..."%>
  <%= form.submit "Search" %>
<% end %>

<ul>
  <% @products.each do |product| %>
    <li>
        Name:<%= product.name %><br>
        Price:<%= product.price  %><br>
        Description:<%= product.description %><br>
        Image:<%= image_tag(product.product_profile, style: 'height:100%;width:auto;') %> <br>
        <% if @current_user.id == product.user_id %>
         This is your product
        <% else %>
        <%= button_to "Buy", buy_purchase_path(product.id), method: :get %>
        <% end %>  
      </li>
  <% end %>

</ul>

  <%= button_to "New Product", new_product_path, method: :get %><br>
  <%= button_to "Back",  products_path, method: :get%>

app/views/products/new.html.erb
<h1>Create Product</h1>

<%= form_with url:'/products', method: :post do |form| %>

  <%= form.label :name  %> <br>
  <%= form.text_field :name  %> <br>

  <%= form.label :description %> <br>
  <%= form.text_area :description %> <br>

  <%= form.label :price %> <br>
  <%= form.number_field :price %> <br>

  <%= form.label :product_profile %> <br>
  <%= form.file_field :product_profile %> <br>
  
  <%= form.label :category %> <br>
 <%= form.collection_select :category_id, Category.order(:category_name), :id, :category_name %><br>
<br> 
  
  <%= form.submit "create" %>
<% end %><br>



  <%= button_to "Back", products_path, method: :get %> <br>

  <%= button_to "Sign_out", users_path, method: :delete %>

app/views/purchases/buy.html.erb
<!-- <h1> </h1> -->



<h1> Product buy sucessfully </h1>

<%= button_to "Back", products_path, method: :get %>

  <%= button_to "Sign_out", "/users", method: :delete %>

app/views/purchases/current_user_sold_products.html.erb
<h1>Purchase products</h1>
<ol>
  <% @purchases.each do |purchase| %>
    <li type=> Name:<%= purchase.name %></li><br>
     Price:<%= purchase.price %><br>

  <% end %>
</ol>


<%= button_to "Back", products_path, method: :get %>
<%= button_to "Sign_out", "/users", method: :delete %>

app/views/purchases/new.html.erb
<h1>Welcome to purchase </h1>

<%= button_to "Back", products_path, method: :get %>

  <%= button_to "Sign_out", "/users", method: :delete %>

app/views/users/new.html.erb
 
<h1>OLX</h1>


<%= form_with url:'/users',method: :post do |form| %>
  <%= form.label :first_name %>
  <%= form.text_field :first_name %> <br>
  <%= form.label :last_name %>
  <%= form.text_field :last_name %> <br>
  <%= form.label :email %>
  <%= form.email_field :email %> <br>
  <%= form.label :password %>
  <%= form.password_field :password %> <br> 
  <%= form.label :mobile_no %>
  <%= form.number_field :mobile_no %> <br>
  <%= form.submit "SignUp" %>
<% end %>

<%= button_to "Signin", signin_users_path, method: :get %>

app/views/users/signin.html.erb
<p style='color:red'> <%= flash[:notice] %> </p>
<%= form_with url:'/users/login',method: :post do |form| %>

  <%= form.label :email %>
  <%= form.email_field :email %> <br>
  <%= form.label :password %>
  <%= form.password_field :password %> <br> 

  <%= form.submit "SignIn" %>
<% end %>
<br>
  <%= button_to "SignUp", new_users_path, method: :get %>